spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
  instance:
    preferIpAddress: true
